### PR TITLE
Localize and convenience

### PR DESCRIPTION
**Pull request by kurisutofu**
+ Updated to latest version of localize
+ Added functions for convenience (getI18N on model)
+ Added functions to add/remove translation for an instance
+ Updated tests to include a new table (to check no impact on other tables) and tests of new functions
- Remove defaultLanguageFallback as it was not used

### CODE REVIEW

**Comment by kurisutofu** [comment]
@nicolascava , I need this updated for a project. Would you be able to merge this PR or should I create a different module for it?

**Comment by nicolascava** [comment]
@kurisutofu sorry for the late reply, I didn't see your comment! Is ok, I'll merge your PR, thank you 🙂

**Comment by nicolascava** [comment]
However, usually, you should follow my conventions (which are not yet documented tho sorry). I'll merge your PR then make some change to fit with the conventions. Thanks.

**Comment by kurisutofu** [comment]
> However, usually, you should follow my conventions (which are not yet documented tho sorry). I'll merge your PR then make some changes to fit with the conventions. Thanks.

@nicolascava thanks! I'll look at the change you made to see where I didn't follow your conventions.

**Pull request merged**
